### ISSUE TITLE
UI shows Version 4.1.3 but 4.1.4 is installed

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa-web#173]
A bit confusing
![image](https://github.com/powa-team/powa-web/assets/34562656/e2887c49-b557-4acd-9eaf-c050aacf7c96)
but 
yum list powa_14-web
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Installed Packages
powa_14-web.x86_64                                                                                                                   **4.1.4**-1.rhel7

**Comment by rjuju** [comment]
Hi,

it's unfortunately a (known) package issue, see https://redmine.postgresql.org/issues/7478.

@devrimgunduz is there anything I can do to help?

**Comment by rjuju** [comment]
Hi @devrimgunduz 

no worries, and thanks for your hard work!

I think that on the apt side there's a powa-archivist package, so having the same name for rpm could be nice but maybe it could lead to some headache when transitioning.  If yes could the powa package become a metapackage that has dependencies on the main extensions, like powa-archivist, pg_qualstats, pg_stat_kcache and pg_track_settings?  I wouldn't put powa-web or powa-collector with it as the remote mode is more useful, so you will probably install those on one or two different servers.

**Comment by devrimgunduz** [comment]
@rjuju ack, thanks! Starting now. I'm not that worried about transition, as the packaging is already broken and we'll keep powa package.

**Comment by rjuju** [comment]
Ah I see, then I agree the transition shouldn't be an issue :)  Thanks a lot!

**Comment by devrimgunduz** [comment]
Should be fixed in the latest release set.

There are now 4 packages (XY stands for PostgreSQL major version):

powa_XY : Meta package (pulls powa_archivist_XY, pg_qualstats_XY, pg_stat_kcache_XY and hypopg_XY (

powa-collector:

powa-archivist_XY

powa-web

Regards, Devrim

**Comment by rjuju** [comment]
Thanks a lot @devrimgunduz !

For the record, I see that you added the last powa-archivist releases (4.2.0 and 4.2.1) but powa-web hasn't been bumped and is still showing 4.1.4.  Is it an oversight or is there anything missing on my side?
