### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by koppaline** [powa-team/powa-web#278]
Hi,

After the start of powa-web and after entering the name/password on the first page, I get a mistake 500. The situation is repeated if you install powa-web from the package, or pip, or from the archive of .tgz (powa-web new version 5.0.1)

(DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS")

```
[I 250220 20:57:49 powa-web:38] Starting powa-web on http://0.0.0.0:8888/
[W 250220 20:57:52 web:2239] 403 GET /login/?next=%2F (10.254.192.127) 18.54ms
[E 250220 20:58:01 web:1789] Uncaught exception POST /login/?next=%2F (10.254.192.127)
    HTTPServerRequest(protocol='http', host='10.254.6.56:8888', method='POST', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='10.254.192.127')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/lib/python3/dist-packages/powa/user.py", line 29, in post
        version = self.get_powa_version(
      File "/usr/lib/python3/dist-packages/powa/framework.py", line 250, in get_powa_version
        version = self.execute(
    IndexError: list index out of range
[E 250220 20:58:01 web:2239] 500 POST /login/?next=%2F (10.254.192.127) 24.79ms
```

**Comment by rmundel** [comment]
Fixed by creating manually the powa extension in the powa database;

**Comment by rjuju** [comment]
was the problem that you never installed the powa extension (and therefore powa-web is missing some explicit check for this) or that it failed to find the extension you did install but somewhere else?

**Comment by rjuju** [comment]
the thing is that the error is related to the powa repository server, and I still don't know how you configured it, which is why I asked more details. 

to try to clarify further, if you didn't install powa on the repository server, then it's obviously not going to work and the problem is that we don't report a useful error. but if you did install powa and you get this error, then something else is going on.

which one is it?

**Comment by koppaline** [comment]
You are right, it was my mistake due to inattention. I installed extensions in the postgres database instead of the powa database.
I would quickly figure out that situation if I had received more useful error messages.
Now everything works for me, thanks! I think the topic can be closed.

**Comment by rjuju** [comment]
ah, thanks for the clarification!

yes I totally agree that the error message as is is entirely useless, fortunately it should be easy to fix.  @pgiraud do you plan to work on that?

on a side note, while it's usually a good idea to isolate the powa data on a dedicated database, nothing prevents you form using the postgres database for that. all would have been needed is to update the config file to point to it (after getting a useful error message saying that powa wasn't found on the configured database and server).

**Comment by rjuju** [comment]
https://github.com/powa-team/powa-web/commit/6cb7b2d93b4eb54e07ec529a3ca5897f1694ed07 should fix the issue.  Feel free to reopen the issue if there is any other problem.
